const EMAIL_MIN_LENGTH = 10;
const EMAIL_MAX_LENGTH = 50;
const PASSWORD_MIN_LENGTH = 5;
const PASSWORD_MAX_LENGTH = 50;

export {
  EMAIL_MAX_LENGTH,
  EMAIL_MIN_LENGTH,
  PASSWORD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
};
