const SCRIPT_NAME_MIN_LENGTH = 3;
const SCRIPT_NAME_MAX_LENGTH = 20;
const SCRIPT_DESCRIPTION_MAX_LENGTH = 100;

export {
  SCRIPT_NAME_MIN_LENGTH,
  SCRIPT_NAME_MAX_LENGTH,
  SCRIPT_DESCRIPTION_MAX_LENGTH,
};
